### ISSUE TITLE
gradio seems not work

### ISSUE THREAD

**Issue by StarsTesla** [sap3d/sap3d#1]
Hi，thanks for your great work！I followed the README install two env and download all ckpt，then I meet alot of bugs.
My only question is that how should I inference on my own images set.
Looking forward a full readme instruction!

**Comment by XinyangHan** [comment]
Hi! We tested the code on different servers, and the code works well on cuda 11.7.  Could you share the error information you faced? (Most likely it is an env error) 

Before testing on new dataset, I recommend replicating the demo experiment we provided for env checking. The inference pipeline is shown in in this file `https://github.com/sap3d/sap3d/blob/main/run_pipeline.sh`. And we recommend testing with command like this; 
![image](https://github.com/sap3d/sap3d/assets/86959032/03130797-dcee-444c-b759-d0540d5c9602)

**Comment by XinyangHan** [comment]
Also, the gradio demo could run up to more than 1 hour, so it do requires some time to wait :)

**Comment by XinyangHan** [comment]
Got it! 

About the bash script for gradio, it should indeed be run_pipeline_demo.sh (which is original version shown in your left image)
I strongly suggest you try demo experiment first, which means you run this command : `sh run_pipeline.sh GSO_demo MINI_FIRE_ENGINE 5 0` in the terminal to see if you can replicate the results.

After you succeed in running demo experiment, you could run new experiments by placing new images in similar folder format.

**Comment by StarsTesla** [comment]
心，累了，哥们
![image](https://github.com/sap3d/sap3d/assets/45264423/7b299565-b186-482a-b056-15a0cda626de)

**Comment by XinyangHan** [comment]
Sorry! Please try this command : `sh run_pipeline.sh GSO_demo Dino_3 5 0`. Also, you can add my wechat 15106297170. I would help you with the problem you faced!
