### ISSUE TITLE
How to run on custimized data?

### ISSUE THREAD

**Issue by cwchenwang** [sap3d/sap3d#2]
Thanks for the great work. I tried to use the gradio demo but it's not working. There seems to be no 'run_pipeline_demo.sh' as in app.py.

**Comment by davidhanx** [comment]
Hey! Thanks for reminding!
1. I just uploaded this script! Nice Catch!
2. I would suggest running command like `sh run_pipeline.sh GSO_demo Crosley_Alarm_Clock_Vintage_Metal 5 0` for testing first to check the env and scripts are clear. (Gradio demo shares similar pipeline so this should be easier to work with)

**Comment by cwchenwang** [comment]
Hi, I already tried to run `sh run_pipeline.sh GSO_demo Crosley_Alarm_Clock_Vintage_Metal 5 0` and everything looks fine.

**Comment by davidhanx** [comment]
Awesome!!

**Comment by davidhanx** [comment]
If everything looks fine using `run_pipeline.sh`, to test new objects, there are two ways:
1. Drop images from the new object to dataset folder in same format as current GSO ones, use `run_pipeline.sh` script, the recon would work similarly if you have pose ground truth like GSO. (This would be used for pose evaluation)
2. You can gradio demo script. (Remember to change the root directory in the `run_pipeline_demo.sh` script :)

**Comment by davidhanx** [comment]
Please feel free to let me know if you have any related questions!

**Comment by cwchenwang** [comment]
Thank you!
