### ISSUE TITLE
Inference GPU memory requirements

### ISSUE THREAD

**Issue by findingpatterns** [sap3d/sap3d#4]
First, thank you for your amazing works !

You have stated that "Memory Considerations: To ensure a smooth operation, your system should have at least 38GB of available memory." 
I wonder that is this the memory requirement for run training or inference phase?
I only have a GPU with 24GB memory. 
Is there anyway to run it

**Comment by davidhanx** [comment]
Hey! The cost of memory comes from 3 parts:

1. Finetuning diffusion model
2. Geometry free nvs
3. Optimizing NeRF with SDS and MSE loss

The 1st and 2nd process have the chance of running on 24gb gpu (they are basically training and inference diffusion model), while the 3nd process would take more gpu memory than that. (Like 38gb)

**Comment by davidhanx** [comment]
So please feel free to try out the 2D nvs part in the pipeline code! (Just comment the 3D optimizing commands in the run_pipeline.sh)
