### ISSUE TITLE
Cannot access one-2-3-45

### ISSUE THREAD

**Issue by alakhag** [sap3d/sap3d#5]
In go_relpose.py, I get following error:
ValueError: Could not fetch config for https://one-2-3-45-one-2-3-45.hf.space/

What is the reason?

**Comment by dufengfeng** [comment]
I also meet the same problem.

**Comment by dufengfeng** [comment]
I also meet the same problem.

**Comment by davidhanx** [comment]
We are borrowing this module from zero12345 (https://github.com/One-2-3-45/One-2-3-45?tab=readme-ov-file)

Checking their issue, I found that there seems to be some problem with their gradio api right now -- https://github.com/One-2-3-45/One-2-3-45/issues/49

I would try to develop other ways to load this api if it still does not work in 2 weeks. I recommend also opening issues under zero12345's repo, checking if the api is still serving~
![image](https://github.com/sap3d/sap3d/assets/86959032/c8550cd2-f5eb-4894-93f2-1d3e3d115757)

**Comment by SiruiXie** [comment]
I solved this issue by cloning the One-2-3-45 to local machine. It is worth noting that the two repos of One-2-3-45 (github repo and huggingface repo) are not identical. One should clone the github repo and get the newer version of app.py script from the huggingface repo.
