### ISSUE TITLE
Version of Pytorch_lightning used in envrionment sap3d

### ISSUE THREAD

**Issue by SiruiXie** [sap3d/sap3d#6]
Excellent work! I like this work very much!
@sap3d 
When I am trying to run the code in `./camerabooth/main.py` with pytorch_lightning==2.3.3, it throws an error:
`ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'`
Then I try to install a lower version 1.5.2, I get annother error:
`TypeError: on_train_epoch_end() missing 1 required positional argument: 'outputs'`
thrown by `pytorch_lightning/trainer/callback_hook.`
Could you please tell me which version of pytorch_lightning should be taken in this repo?

Looking forward to your reply

**Comment by davidhanx** [comment]
Hi! Thanks for your interest! We tested and wrapped our env here `https://github.com/sap3d/sap3d/blob/main/docs/INSTALL.md`. I suggest checking this doc and see how it goes~

**Comment by SiruiXie** [comment]
> Hi! Thanks for your interest! We tested and wrapped our env here `https://github.com/sap3d/sap3d/blob/main/docs/INSTALL.md`. I suggest checking this doc and see how it goes~

Thanks for your quick reply.
I have double checked your installation guidance, but I still find no notion about version of pytorch_lightning in your `environment_sap3d.yml` file.

**Comment by davidhanx** [comment]
Got it! We use `pytorch-lightning==2.0.0` for sap3d env!

**Comment by SiruiXie** [comment]
> Got it! We use `pytorch-lightning==2.0.0` for sap3d env!

But as far as I know, in version 2.0.0, pytorch_lightning.trainer.Trainer object has no attribute `add_argparse_args` (see in ./camerabooth/mainpy:937), and for now I have no idea hot to fix this. Also, `rank_zero_only` in `pytorch_lightning.utilities.distributed` has been moved into `pytorch_lightning.utilities` (see in ./camerabooth/mainpy:38)

**Comment by davidhanx** [comment]
Oh! If it is for camerabooth, we use `zero123`'s env, see the pipeline here: sap3d/run_pipeline.sh
![image](https://github.com/user-attachments/assets/b6871432-702c-4f77-b631-00af3e53c3b6)

**Comment by SiruiXie** [comment]
> Oh! If it is for camerabooth, we use `zero123`'s env, see the pipeline here: sap3d/run_pipeline.sh ![image](https://private-user-images.githubusercontent.com/86959032/349416615-b6871432-702c-4f77-b631-00af3e53c3b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDQwMzQsIm5iZiI6MTcyMTIwMzczNCwicGF0aCI6Ii84Njk1OTAzMi8zNDk0MTY2MTUtYjY4NzE0MzItNzAyYy00Zjc3LWI2MzEtMDBhZjNlNTNjM2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4MDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NmUxM2Q5MTc5NzYzNzZlM2E2OGI4YWY1N2MxODQ2YmJhNTBjMmFmMWRhYWQwZWU2YzI1OGE3YzYwNGY4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ePyjwDhMNx7_4myqtamK8k_u2JtSfnFW73EQFRYlog)

Oh, then... Haha Thank you😅
